### ISSUE TITLE
step 7 debug

### ISSUE THREAD

**Issue by erenada** [SchwartzLabURI/SISRS#26]
while running step 7: 

Output error:

```
grep: /data/schwartzlab/eren/Evolution21/SISRS_Run/AnaPla/err_AnaPla_SISRS: No s
uch file or directory
...
FileNotFoundError: [Errno 2] No such file or directory: XX/XX/"out_XX_SISRS' 
```

Reason: Rachel's script for the 6th step doesn't create out_XX_SISRS file. Yana's version used to do.

**Comment by rachelss** [comment]
Error due to using a prior version.
