### ISSUE TITLE
hidden bug at 6th step w new version (directory issue)

### ISSUE THREAD

**Issue by erenada** [SchwartzLabURI/SISRS#27]
When running step 6, the analysis looks to run well for a while. There are ".bam" files in taxon folders. So, "bowtie" step looks to be working. (path to analyses: /data/schwartzlab/eren/Chapter2)

Then when the script tries to run "samtools" function, there is an error message:

"(ERR): Argument expected in next token!
Exiting now ...
[main_samview] fail to read the header from "-".
samtools sort: failed to read header from "-"
sh: /data/schwartzlab/eren/Chapter2/SISRS_Run/TrimReads/TrimReads_Temp.bam_Header.sam: No such file or directory"

Output file says:

['bowtie2 -p ', '20', ' -N 1 --local -x ', '/data/schwartzlab/eren/Chapter2', '/SISRS_Run/Composite_Genome/contigs -U ', '', ' | samtools view -Su -@ ', '2
0', ' -F 4 - | samtools sort -@ ', '20', ' - -o ', '/data/schwartzlab/eren/Chapter2/SISRS_Run/TrimReads/TrimReads_Temp.bam']

Problem: There is no "TrimReads" folder in the SISRS_Run folder. It is at 2 directories up. Looks like the directories in the python script were written for the previous version's file structure. In the previous version, there are trimmed reads in each SISRS_Run/TAXA folder and the script was taking these as input. In the new version, the script is intended to get input files directly from OUTFOLDER/Reads/TrimReads/TAXA.  In @rachelss version of the 6th steps python script, "outbam" or "outbamb" needs to be fixed.

**Comment by erenada** [comment]
out and error logs can be found at:

/data/schwartzlab/eren/Chapter2/SISRS/scripts/slurm_submissions/6_step_66534_31.out

/data/schwartzlab/eren/Chapter2/SISRS/scripts/slurm_submissions/6_step_66534_31.err

**Comment by rachelss** [comment]
Fixed issues with / in the slurm scripts that would omit the last two alignments.
